site_name: ReCaS-Bari HPC/GPU Cluster
repo_url: https://github.com/jvino/cluster-hpc-gpu-guides
site_author: Gioacchino Vino - gioacchino.vino@ba.infn.it
theme:
  name: material
  palette:
    primary: teal
    accent: orange
  logo: assets/logo_infn.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
   
nav:
  - Overview: 'index.md'
  - Interactive Services: 
    - ReCaS JupyterHub: 'interactive_services/jupyter-lab-for-recas-users-k8s.md'
    - ReCaS JupyterHub with powerful GPUs: 'interactive_services/jupyter_with_gpu.md'
    - RStudio: 'interactive_services/rstudio.md'
  - Job Submission:
    - Using Kubernetes: 'job_submission/k8s-jobs.md'
  - Guides:
    - Docker and Dockerfile: 'guides/docker_and_dockerfile.md'
    - JupyterLab: 'guides/jupyter-lab.md'
 
copyright: Copyright &copy; 2024 INFN
