site_name: ReCaS-Bari HPC/GPU Cluster
repo_url: https://github.com/jvino/cluster-hpc-gpu-guides
site_author: Gioacchino Vino - gioacchino.vino@ba.infn.it
theme:
  name: material
  palette:
    primary: teal
    accent: orange
  logo: assets/logo_infn.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
   
nav:
  - Intro: 'index.md'
  - Interactive Services: 
    - ReCaS Jupyter Lab (Work in progress): 'interactive_services/jupyter-lab-for-recas-users.md'
    - Custom Jupyter Lab (Work in progress): 'interactive_services/jupyter_lab.md'
    - Jupyter Notebook: 'interactive_services/jupyter_notebook.md'
    - RStudio: 'interactive_services/rstudio.md'
  - Job Submission:
    - Chronos: 'job_submission/chronos.md'
  - Guides:
    - Docker and Dockerfile: 'guides/docker_and_dockerfile.md'
    - Jupyter Lab: 'guides/jupyter-lab.md'
 
copyright: Copyright &copy; 2022 INFN
